In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,4])

print(A.ndim) # 스칼라 = 0, 1차원 배열 = 1!
print(A.shape) #  각 차원의 크기 리턴. (4, ) => 1차원에 4개 개수의 원소가 있다
print(A.shape[0]) 

1
(4,)
4


In [4]:
B = np.array([
    [1,2],[3,4],[5,6]
])

print(B.ndim) # 2
print(B.shape) # 3 2 -> 3행 2열

2
(3, 2)


In [6]:
# 행렬곱 = dotProduct
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [8]:
#행렬곱 2
A = np.array([[1,2,3],[4,5,6]]) # (2,3)
B = np.array([[1,2],[3,4],[5,6]]) # (3,2)
print(np.dot(A,B))

[[22 28]
 [49 64]]


In [9]:
# 신경망에서의 행렬곱(편향, 활성화함수 배제)
X = np.array([1,2]) 
W = np.array([[1,3,5],[2,4,6]]) 
print(X.shape, W.shape)

(2,) (2, 3)


In [11]:
Y = np.dot(X,W)
print(Y)

[ 5 11 17]


In [ ]:
X = np.array([1.0,0.5]) # 1행 2열
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]]) # 2행 3열
B1 = np.array([0.1,0.2,0.3])

In [17]:
print(W1.shape, X.shape, B1.shape)

A1 = np.dot(X, W1) + B1
print(A1)

(2, 3) (2,) (3,)
[0.3 0.7 1.1]


In [18]:
# 시그모이드 활성화 함수를 위 신경망 행렬곱 예제에 적용시켜보자
def sigmoid(x):
    return 1/ (1+np.exp(-x))


In [19]:
Z1 = sigmoid(A1)
print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [21]:
# 이제 2층

W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])

print(Z1.shape, W2.shape, B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
print(Z2)

(3,) (3, 2) (2,)
[0.62624937 0.7710107 ]


In [22]:
# 2층 -> 출력층으로의 신호 전달
def identity_function(x):
    return X

W3 = np.array([[0.1,0.3], [0.2,0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3) 
# 출력층은 딱 하나, 활성화 함수로 시그모이드같은게 아니라 항등함수를 사용한다!
# 다만 풀고자 하는 task, 즉 회귀냐 분류냐에 따라 항등함수, 소프트맥스 등 다양하게 사용한다!

In [26]:
def init_network():
    # 네트워크 초기화 함수입니다. 가중치와 편향을 딕셔너리에 저장합니다.
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return network

def forward(network, x):
    # 순전파 함수입니다. 입력 x를 받아 네트워크를 통해 출력 y를 계산합니다.
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    # 첫 번째 층의 계산
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)

    # 두 번째 층의 계산
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)

    # 세 번째 층의 계산
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)

    return y

In [29]:
network = init_network()
x=np.array([1.0,0.5])
y=forward(network, x)
print(y)

[1.  0.5]


In [33]:
# 소프트맥스 함수 - 분류에서의 출력층에서 사용하는 활성화함수 (오버플로 미고려 버전)

def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    return exp_a / sum_exp_a

softmax(np.array([0.3,2.9,4.0]))

array([0.01821127, 0.24519181, 0.73659691])

In [34]:
a=np.array([1010,1000,990])
np.exp(a)/ np.sum(np.exp(a))

/var/folders/8g/grq3jkbd5hb_jdz3kql04_yr0000gn/T/ipykernel_90884/3521604395.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a)/ np.sum(np.exp(a))
/var/folders/8g/grq3jkbd5hb_jdz3kql04_yr0000gn/T/ipykernel_90884/3521604395.py:2: RuntimeWarning: invalid value encountered in divide
  np.exp(a)/ np.sum(np.exp(a))


array([nan, nan, nan])

In [35]:
c = np.max(a) # 오버플로를 막기위해 지수함수 지수의 임의수를 더한다. 여기선 a에서 max값의 음수
a - c 

array([  0, -10, -20])

In [36]:
def softmax(a): # 오버플로 고려한 버전
    c=np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a=np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

## 소프트맥스 함수의 특징
- y가 0, 1사이로 나온다.
- 또한 출력 총합이 1이 된다!! => 함수의 출력을 '확률'로 해석가능 => 분류에서 쓰이는 이유
- 다만 학습단계에서만 쓰이고 완성형 모델인, 즉 추론단계에선 지수함수계산 자원낭비 방지를 위해 생략한다 => 어차피 단조증가 함수라 대소관계가 변하지 않음
